### ISSUE TITLE
pepper 로고 만들기

### ISSUE THREAD

**Issue by yoonjieun** [lazypic/pepper#1]

**Comment by yoonjieun** [comment]
![pepper](https://cloud.githubusercontent.com/assets/15062415/26753015/0abb4292-4898-11e7-8cd9-f40bc6015b1a.png)

**Comment by khw7096** [comment]
역시 다른 로고가 더 잘 어울릴듯. 로고는 페퍼 울트라 라이트 안쪽 정면 사각형 프레임안에 캐드를 이용해서 넣을 예정이다.

**Comment by khw7096** [comment]
![new_logo](https://user-images.githubusercontent.com/1149996/27991594-fa40f9b2-64b6-11e7-9096-692220d963ed.png)

**Comment by irenebaek** [comment]
요 ! 13 ?

**Comment by khw7096** [comment]
13인치의 줄임말이예용. pepper ultra light가 너무 긴 느낌이 있는데 어떤 이름이 좋을것 같아요?

**Comment by khw7096** [comment]
아직 결정을 하기전에 고민하는 중이랄까..

**Comment by kybin** [comment]
인치라니!

센치가 국제 표준입니다

**Comment by khw7096** [comment]
아직 애플의 세계를 모르시네...ㅋㅋㅋ

**Comment by kaycho** [comment]
구멍을 내는 방식으로 로고를 넣을 수 있다면 좋겠습니다. 인쇄 방식 보다 더욱 환경 친화적입니다.

1. 통풍을 고려한 위치 로고 모양으로 뚫는다.
2. 구멍을 뚫지 못하는 경우 로고모양으로 뚫린 종이(떨어져 나온 종이도)를 붙인다.

구멍내는 방식에 적합한 로고를 만들어야 하는 이슈가 있습니다.

**Comment by khw7096** [comment]
오 좋은 아이디어예요! 로고가 더 심플해야겠네요. 나중에 칼선 제작을 하려면...

**Comment by khw7096** [comment]
다른 제품과 마찬지로 레이지픽 캐릭터 "pepe" 가 담당하여 이 제품을 메니징한다.

**Comment by khw7096** [comment]
구멍을 내는 로고의 단점은 개인이 작업하기에는 불편하다. 공장에서 일괄 처리 해야한다.
손쉽게 만드는 방법에서 벗어나는 것 같다.

**Comment by khw7096** [comment]
로고는 좋은 아이디어가 발생할 때 다시 이슈로 열겠습니다.
