### ISSUE TITLE
catchphrase 정하기.

### ISSUE THREAD

**Issue by khw7096** [lazypic/pepper#15]
- protect your neck and nature. : 웅
- save earth save us. : 윤지( help earth, help us를 따라한글임.)
- abnormal flavor paper project : 용빈

**Comment by kaycho** [comment]
tree paper tree

**Comment by khw7096** [comment]
드디어 참여인가요?!!

**Comment by kybin** [comment]
좋네요

**Comment by kybin** [comment]
abnormal 보단 unique가 나은것 같아요.

unique flavored projects with paper

**Comment by khw7096** [comment]
프로젝트 목표가 catchphrase 보다 중요하다.
Readme.md에 목표를 명확하게 작성함.
