### ISSUE TITLE
참고자료

### ISSUE THREAD

**Issue by khw7096** [lazypic/pepper#9]
http://www.ntrexgo.com

**Comment by khw7096** [comment]
종이책상 : http://blog.naver.com/bethy_/220220796439

**Comment by khw7096** [comment]
트러스트 아치 구조는 A4 두장으로 1.4kg을 버틴다.

**Comment by khw7096** [comment]
종이스톨

http://storefarm.naver.com/shanghaimall/products/453966608?NaPm=ct%3Dj3lpxp0o%7Cci%3D7912d56a08370b75f120976907532da5ca5a325a%7Ctr%3Dsls%7Csn%3D349772%7Chk%3Df403cfa88844c6ffa33ea81b0031c081b3eeb5b5

**Comment by khw7096** [comment]
오조 그린시트

http://item.gmarket.co.kr/DetailView/Item.asp?goodscode=685282086&GoodsSale=Y&jaehuid=200001169&NaPm=ct%3Dj3lpzh28%7Cci%3D7590a86089121c1f2702ef1d8f4860eec52e3983%7Ctr%3Dligh%7Csn%3D24%7Chk%3D2869b837d7d7dd17b8fdab9e1e96b2c432d7426a

**Comment by khw7096** [comment]
종이책상

http://firstsci.co.kr/product/detail.html?product_no=21680&cate_no=62&display_group=1&cafe_mkt=naver_ks&mkt_in=Y&ghost_mall_id=naver&ref=naver_open&NaPm=ct%3Dj3lq5na8%7Cci%3D13ce62af4eb6677bea9b5c5f06ad6c064d9fc1bb%7Ctr%3Dslsl%7Csn%3D476632%7Chk%3Ddf2a28e7a0fe041224727066f6e9697623869d25

http://funnyschool.co.kr/youngcart4/shop/item.php?it_id=1215687615&NaPm=ct%3Dj3lq6i5c%7Cci%3Dd7d48ca23d65b59c9d129e2c83c409b75d2c0fbb%7Ctr%3Dslsl%7Csn%3D357544%7Chk%3Df9fbd029aa77a7cccbcfb22aac6cc430b04df5fd

**Comment by kybin** [comment]
좋은 레퍼런스들이네요. 특히 refold제품들이 좋은듯. refold라는 이름도 좋구요.
